### ISSUE TITLE
https://www.mdavis.xyz/govlist/

### ISSUE THREAD

**Issue by HellenisticWarrior** [mdavis-xyz/mdavis.xyz#21]
A brilliant list but add -
The Futures Fund being used to supply weapons to Myanmar's military
The $18 million given with no documents, no papers etc etc to the GG (?) and 3 mates
The $5 billion NON subs loss - at least some is going to Peter Costello and mates

**Comment by mdavis-xyz** [comment]
> The Futures Fund being used to supply weapons to Myanmar's military

I already have a few points about Myanmar funding. Is this a duplicate? I didn't know it was coming from the Future Fund. Or is this an additional spend?

e.g. the page currently says:

 Spent $400,000 to help train the Myanmar military, who were known to be guilty of ongoing genocide against the Rohingya people, and were later responsible for a literal coup to overthrow their government, including shooting and killing hundreds of peaceful anti-coup protestors. source source source [link](https://www.theguardian.com/australia-news/2018/mar/06/australia-to-train-myanmar-military-despite-ethnic-cleansing-accusations) [link](https://www.thejakartapost.com/seasia/2021/02/16/myanmar-situation-not-what-china-wants-to-see-ambassador-.html) [link](https://edition.cnn.com/2021/02/27/asia/myanmar-un-ambassador-fired-intl-hnk/index.html)

> The $18 million given with no documents, no papers etc etc to the GG (?) and 3 mates

Who are GG? Governor General? Can you provide more information please, especially links.

> The $5 billion NON subs loss - at least some is going to Peter Costello and mates

What's the context here? Is this a termination fee with the french?

**Comment by Peter-Lander** [comment]
I found no reference to the fact that AUKUS - the defense treaty, not the submarines order - was agreed to without Parliamentary oversight and with no discussion about its impact on ANZUS. The actual wording of this treaty seems to be invisible. The press releases from USA, Australia, and UK differed in detail - tending to justify the view that no formal agreement exists even now.

**Comment by mdavis-xyz** [comment]
Is this the wording of the treaty?

https://www.aph.gov.au/-/media/02_Parliamentary_Business/24_Committees/244_Joint_Committees/JSCT/2021/AUKUS_ENNPIA/2_AUKUS_treaty_text.pdf?la=en&hash=DE9C7BF15754F72E42A611ECAE86699D5A4F9216

**Comment by Peter-Lander** [comment]
No it is not. It plainly is not. Firstly, it relates solely to the nuclear subs - not the defense treaty. Remember, that is what I asked about. Secondly, it is not even the agreement about the submarines - it is an agreement about keeping submarine data secret.

I am actually fairly impressed that you got your hands on this document. This unsigned document.

Australia's future is not in jeopardy because of half a dozen subs that we'll probably never see.
I worry about what those three knuckleheads dreamed up by way of a tripartite alliance where I fully expect that Australia will be a massive loser.

What is the nature of the AUKUS agreement that is still being kept secret from us poor yobboes who must pay the price?
That is the question.

**Comment by mdavis-xyz** [comment]
Added, will publish later today

**Comment by Peter-Lander** [comment]
I only noticed your addition today. A belated thank you.
